ports:
  - port: 3000
    onOpen: open-browser
  - port: 10000
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn
    command: |
      echo "Applying a temporary workaround until https://github.com/vitejs/vite/pull/1992 is fixed"
      (
        cd ./node_modules/vite/dist/node/chunks/ &&
        sed -i 's/JSON.stringify(port)/JSON.stringify(443)/g' * &&
        export WSS_HOST=`gp url 24678 | sed 's#https://##g'` &&
        sed -i "s#JSON.stringify(host)#JSON.stringify(\"$WSS_HOST\")#g" *
      )
      yarn dev

vscode:
  extensions:
    - svelte.svelte-vscode@104.12.1:e36e8a1b48e34a2e062a7a324bf8f153
    - vscodevim.vim@1.20.2:a890e275dc0d6f05f4ea731538fd43fc