image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 24678
    visibility: public
    onOpen: ignore
  - port: 10000
    visibility: public
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn
    command: |
      export HMR_HOST=`gp url 24678`
      yarn dev

vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
